# Generated by Django 2.1.1 on 2018-11-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_title', models.TextField(max_length=1000)),
                ('crime_description', models.TextField()),
                ('date_of_crime_happened', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(verbose_name='Date of Birth')),
                ('place_of_birth', models.CharField(max_length=1000)),
                ('nationality', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5)),
                ('passport_number_or_residence_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PCCApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_request', models.TextField(max_length=2000)),
                ('clearance_requested_by', models.TextField(max_length=1000)),
                ('reference_number', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(help_text='Please use the following format: <em>MM/DD/YYYY</em>.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceBiometricsApp.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='crime',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceBiometricsApp.Customer'),
        ),
        migrations.AddField(
            model_name='pccapplication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceBiometricsApp.Customer'),
        ),
    ]
